### ISSUE TITLE
Basic HTML

### ISSUE THREAD

**Issue by plim3019** [plim3019/BSIT-TSM-3A-IPT2CS-G3#4]
Upload a screenshot of your HTML progress here:

**Comment by dvregalado** [comment]
![image](https://github.com/plim3019/BSIT-TSM-3A-IPT2CS-G3/assets/159202364/3fd4680c-f080-4950-bb88-31ea8723f2fd)
![image](https://github.com/plim3019/BSIT-TSM-3A-IPT2CS-G3/assets/159202364/9bd542da-5c1e-4cc5-bf90-b88c41611f99)
